# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor, random_tensor.shape

(tensor([[0.9461, 0.1776, 0.6992, 0.3515, 0.1830, 0.0778, 0.5377],
         [0.8571, 0.5379, 0.2688, 0.1617, 0.0167, 0.1562, 0.4073],
         [0.6927, 0.1837, 0.6757, 0.9934, 0.0143, 0.8800, 0.2447],
         [0.7552, 0.5974, 0.5589, 0.7433, 0.8282, 0.3970, 0.4678],
         [0.8183, 0.2379, 0.7490, 0.7215, 0.0932, 0.8493, 0.4067],
         [0.9692, 0.3065, 0.6891, 0.0878, 0.7914, 0.3150, 0.4164],
         [0.2459, 0.4762, 0.9928, 0.7703, 0.9488, 0.9259, 0.9252]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor2 = torch.rand((1,7))

# Perform matrix multiplication
random_tensor*random_tensor2

tensor([[0.3075, 0.1236, 0.3764, 0.0328, 0.1460, 0.0459, 0.0211],
        [0.2786, 0.3743, 0.1447, 0.0151, 0.0134, 0.0923, 0.0160],
        [0.2251, 0.1278, 0.3638, 0.0927, 0.0114, 0.5198, 0.0096],
        [0.2455, 0.4156, 0.3009, 0.0694, 0.6606, 0.2345, 0.0183],
        [0.2660, 0.1655, 0.4032, 0.0674, 0.0743, 0.5017, 0.0159],
        [0.3150, 0.2132, 0.3709, 0.0082, 0.6312, 0.1861, 0.0163],
        [0.0799, 0.3313, 0.5345, 0.0719, 0.7567, 0.5469, 0.0363]])

In [4]:
random_tensor2.shape, random_tensor2.T.shape

(torch.Size([1, 7]), torch.Size([7, 1]))

In [5]:
random_tensor.mm(random_tensor2.T)

tensor([[1.0532],
        [0.9342],
        [1.3502],
        [1.9447],
        [1.4940],
        [1.7409],
        [2.3575]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
r1 = torch.rand((7,7))
r2 = torch.rand((1,7))

# Matrix multiply tensors
t = r1.mm(r2.T)
t.shape,t.dtype,t.device

(torch.Size([7, 1]), torch.float32, device(type='cpu'))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

# Create two random tensors
r1 = torch.rand((7,7))
r2 = torch.rand((1,7))

# Matrix multiply tensors
t = r1.mm(r2.T)
t

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [26]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
# import argparse

# parser = argparse.ArgumentParser(description='PyTorch Example')
# parser.add_argument('--disable-cuda',  required=False,action='store_true', help='Disable CUDA')
# parser.add_argument("-f", required=False)
# args = parser.parse_args()

# args.device = None
# if not args.disable_cuda and torch.cuda.is_available():
#     args.device = torch.device('cuda')
# else:
#     args.device = torch.device('cpu')

device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU


'cuda'

In [27]:
tensor = torch.rand((2, 3))
tensor2 = torch.rand((2, 3))

print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu2 = tensor2.to(device)

tensor_on_gpu, tensor_on_gpu2

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [28]:
torch.cuda.device_count()

1


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [31]:
# Perform matmul on tensor_A and tensor_B
mm_t = tensor_on_gpu.mm(tensor_on_gpu2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [33]:
# Find max
mm_t.max(), mm_t.min()
# Find min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [34]:
# Find arg max
mm_t.argmax(),mm_t.argmin()

# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [38]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_t = torch.rand((1, 1, 1, 10))
print(random_t.shape)
# Remove single dimensions
random_t2 = random_t.squeeze()
print(random_t2.shape)

# Print out tensors and their shapes
random_t2, random_t

torch.Size([1, 1, 1, 10])
torch.Size([10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]))